### ISSUE TITLE
Configure and build commands run twice

### ISSUE THREAD

**Issue by wanderer2** [deprint/build-tools-cpp#10]
Hello. Since the last release, all commands seem to be running twice. I am using the latest version of Atom and this package.

**Comment by deprint** [comment]
I cannot reproduce the issue with the latest version and Atom.
What do you mean with running twice ?
Does the console output show twice or does the console command execute twice ?

**Comment by wanderer2** [comment]
Both. Output showed up twice, so I checked via the "top" command and confirmed that command also executed twice. It doesn't always happen, I myself are having a hard time reproducing the issue. I'll let you know if I find what triggers such behavior.
