### ISSUE TITLE
How to set build commands

### ISSUE THREAD

**Issue by andrewpcone** [deprint/build-tools-cpp#11]
I can't figure out how to make this package run a specific command. Like say I want my build command to be `gcc foo.c`.

What exactly do I do? It's not clear to me from the readme or the settings view.

**Comment by andrewpcone** [comment]
atom 0.176.0, build-tools-cpp 1.0.1.
This is all I see in settings. But I see there's a `SettingsView` in the code that I can't figure out how to make appear.
![screen shot 2015-01-29 at 4 07 04 pm](https://cloud.githubusercontent.com/assets/1505330/5968827/f56281f4-a7d0-11e4-87ea-dee5327e18e2.png)

**Comment by deprint** [comment]
There are three ways to open the settings:
1. `Packages` menu -> Build tools C/C++ -> Show build settings
2. Open the command palette -> `Build Tools Cpp: Settings`
3. Click the small arrow in the package's title bar
![screenshot from 2015-01-30 06 46 22](https://cloud.githubusercontent.com/assets/7817714/5971703/b7aa6978-a84b-11e4-9721-61d3f71a2c9e.png)
