### ISSUE TITLE
Uninstalling and installing causes duplicate keybindings in settings list

### ISSUE THREAD

**Issue by andrewpcone** [deprint/build-tools-cpp#12]
![screen shot 2015-01-29 at 4 00 41 pm](https://cloud.githubusercontent.com/assets/1505330/5968760/1933d5a2-a7d0-11e4-9f64-0b33b58bac28.png)

**Comment by andrewpcone** [comment]
atom 0.176.0, build-tools-cpp 1.0.1

**Comment by deprint** [comment]
I can replicate this issue with other packages too, so I assume the bug is not my fault.
Fortunately this only seems to be a display error which can be fixed by restarting atom.
