### ISSUE TITLE
Support for ninja

### ISSUE THREAD

**Issue by Kuxe** [deprint/build-tools-cpp#16]
I prefer [ninja](https://github.com/martine/ninja) over make. Support for ninja (as in highlighted build output + clickable links to sources in build output) would be fantastic :).

**Comment by deprint** [comment]
Most build systems (Makefile, g++ commands, ...) use stderr to show compiler errors and my package only highlights messages in stderr. The only problem is that ninja does not seem to use stderr at all(?).
I currently have not much to do, so I'll see what I can do.

**Comment by Kuxe** [comment]
Thank you very much!
