### ISSUE TITLE
Build folder not found,

### ISSUE THREAD

**Issue by likask** [deprint/build-tools-cpp#18]
Package worked great, but at some point I can't build any more. 

Trying to build I get message that build folder can not be found. Restarting atom has not resolve problem, however closing project and restarting atom did a trick and solved problem,

**Comment by likask** [comment]
I restarted atom several times, this not resolve problem, However closing and opening project magically resolve issue.

**Comment by deprint** [comment]
Did you enter a relative or absolute path?
If you entered an absolute path, maybe try a path relative to the project's root folder and see if that helps.

**Comment by likask** [comment]
Problem resolved itself. However it didn't work for any path, absolute or reference. This is very minor issue. Closing project and starting again in atom somehow make build tools work again.

**Comment by deprint** [comment]
I hope the issue fixes itself when I release the next major update in 1 or 2 weeks.
