### ISSUE TITLE
build triggers save of all open buffers, not just unmodified

### ISSUE THREAD

**Issue by ssfrr** [deprint/build-tools-cpp#21]
This bumps the timestamp on all open buffers and triggers a re-build from make, even if the files aren't edited. It seems like it would be better to only save the modified buffers.

**Comment by deprint** [comment]
I think this is a problem related to atom/atom#2871, but I think I'll have to change my code because AFAIK they had a reason for saving unmodified files.

**Comment by ssfrr** [comment]
Great, thanks!
