### ISSUE TITLE
Panel doesn't shrink anymore once it's expanded.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [deprint/build-tools-cpp#26]
Hello

I've noticed a very small oddity with the recently released 3.2.0; I can reproduce it using the following steps:

  * Open a project that built successfully last time (or will build successfully).
  * Start building, the small progress bar pops up at the bottom (which looks very neat by the way).
  * Cause an error the code and build again. The progress bar pops up again and the panel expands, as to make room for displaying the error output of the command. So far so good.
  * Fix the error and build again. You are now 'stuck' with the large panel that contains no output but is displayed anyway.

Thanks in advance

**Comment by deprint** [comment]
Yes I can confirm this issue. I did not notice it because every build system I use prints a few lines regardless of compilation status so the panel always showed up. Fix on the way.
