### ISSUE TITLE
Bug in profile doc page

### ISSUE THREAD

**Issue by go2sh** [deprint/build-tools-cpp#34]
Hey,

I just had a look at the Profile Wiki Page. It seams that the provideProfile code example has some copy-and-paste error.
````
provideLinter: ->
  key: 'test' # Unique key for internal use
  profile: require './profile' # Profile class
````
I think 'provideProfile' shoult be correct. Maybe the part needs also some more explanation like https://github.com/atom/autocomplete-plus/wiki/Provider-API.
Regards,
Chris

**Comment by deprint** [comment]
Yes that was a copy-and-paste error ... other than that I don't know how much more explanation is necessary, considering that most compilers have a syntax that is more or less similar to the core profiles (and I advise anyone who wants to provide a profile to pick one of the core profiles as a template).
If you or anyone else has problems understanding highlighting profiles then please tell me so I can improve the interface and the documentation.

**Comment by deprint** [comment]
I'll close this because the original bug was fixed and there is a new wiki without the old bugs.
