### ISSUE TITLE
Command not running

### ISSUE THREAD

**Issue by alextorre98** [deprint/build-tools-cpp#38]
When I try to execute any comand I get an error saying "recieved error: spawn C:\WINDOWS\system32\cmd.exe ENOENT". Running Atom 1.0.19 on windows 10 32-bit.

![captura de pantalla 2](https://cloud.githubusercontent.com/assets/8521669/10264885/de5f1adc-6a1a-11e5-9f66-7e8524bbf06c.png)

**Comment by deprint** [comment]
Can you post the command's configuration ?
Do you use wildcards ?

**Comment by alextorre98** [comment]
Yes, I use wildcards. This is my command config:
![captura de pantalla 5](https://cloud.githubusercontent.com/assets/8521669/10265068/129cd0cc-6a21-11e5-97f3-9a180fac8895.png)

**Comment by deprint** [comment]
build-tools (at least the current version) stores most of its configuration in a file called `build-tools-cpp.projects

**Comment by deprint** [comment]
build-tools stores most of its commands in a file called `build-tools-cpp.projects`. My guess is that this file somehow got corrupted. My guess is that the project path is somehow wrong and the easiest solution would probably be to set the `Working Directory` to the absolute folder path.

**Comment by alextorre98** [comment]
Problem solved by creating new project in separate folder, thanks for the help!

**Comment by deprint** [comment]
As I said, its probably a corrupt config file. I'll release the next major update this month which won't rely on said config file anymore, so issues of this kind should resolve themselves.
