### ISSUE TITLE
No console output when running a command

### ISSUE THREAD

**Issue by marvinroger** [deprint/build-tools-cpp#40]
Each command (even a simple `echo test`) doesn't output anything to the console output. But the command is ran.

I am using build-tools 4.0.3 on Atom 1.0.19 on Ubuntu 14.04 x64 up-to-date.

**Comment by deprint** [comment]
Did you enable console output ?
There is a list at the bottom of the command edit screen where you can enable output modules.

**Comment by marvinroger** [comment]
I do feel dumb right now. I am on a small screen so I didn't see the config was scrollable.
Sorry for the noise.
