### ISSUE TITLE
issue installing

### ISSUE THREAD

**Issue by richardsonchrisj** [deprint/build-tools-cpp#45]
I'm wondering if there's anything I can do to fix this install error I'm getting. 
This is what it looks like. 

npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by deprint** [comment]
Looks like this issue is related to your internet connection.
Did you try it again after a few minutes ?

**Comment by richardsonchrisj** [comment]
Thanks. I still haven't been able to download it. But I have it on my laptop so I was able to copy and paste the package files onto my desktop.

**Comment by deprint** [comment]
Your laptop was able download the latest version or did you downgrade the package ?

**Comment by richardsonchrisj** [comment]
My laptop already had an earlier version. Neither computer, at home or at work, is able to download the latest version. They are both on 4.2.3.
