### ISSUE TITLE
Doesn't seem to work anymore with Atom 1.2

### ISSUE THREAD

**Issue by noirbizarre** [deprint/build-tools-cpp#46]
Hi !

Since I upgraded to Atom 1.2, build-tools doesn't seem to work anymore:
I have the following error in the console:
```
/usr/share/atom/resources/app.asar/src/package.js:655 Failed to require the main module of 'build-tools' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.
```

**Comment by deprint** [comment]
You probably have to rebuild the module. There should be a bug indicator in the status-bar that allows you to rebuild the package (including the new dependency).

**Comment by noirbizarre** [comment]
You're right. Sorry for the inconvenience.
