### ISSUE TITLE
There is no "Add Provider" option.

### ISSUE THREAD

**Issue by isopropylcyanide** [deprint/build-tools-cpp#52]
I can't be the only one. After installing this package as well as the atom-build package, I try to follow the steps mentioned to create a custom build.
But when I create a new file " .build-tools.cson ", there is no option to add a provider. What am I doing wrong?

**Comment by deprint** [comment]
What version of atom are you using ? Operating System ?
Did the package activate properly after the installation (if not, try to restart atom) ?
Are there any error messages related to my package in the developer console (`View->Developer->Toggle Developer Tools`) ?

**Comment by isopropylcyanide** [comment]
Version : 1.3.2
    OS:         Linux Mint 17.3 (64 Bit)
Yes, it activated properly, suffice to say there were no errors at least. It popped up a message saying that  there were no build files currently. So, I went ahead to create one using the instructions mentioned in your readme page. 
But, there just doesn't seem to be an "Add Provider" button to click upon. Nothing appears like that in the sample gif.
![screenshot from 2016-01-02 20 37 55](https://cloud.githubusercontent.com/assets/12872673/12074840/be75aaca-b190-11e5-8561-144b32eb0760.png)

**Comment by deprint** [comment]
Did you open the file before installing the package ? If so, you'll have to close the tab and open the file again.

I'm working with `1.4.0-beta0` without problems but I'm currently compiling `1.3.2` to see if anything's changed there.

BTW the popup that there were no build files currently is from `atom-build`, which has nothing to do with my package. It's completely seperate.

**Comment by isopropylcyanide** [comment]
I appreciate your swift reply. But I opened the file only after I installed the package. Restarted many a times. Sorry for bringing the other package's error into your thread. Seems like everything has been messed up. 
The thing is I just want to be able to build my c++ using my custom flags on the fly. But due to the inexistence of any reliable bulld system management in Atom (unlike Sublime), I had to wander for long until I stumbled upon yours which I figured would be just what I needed.

**Comment by deprint** [comment]
Alright ... I'm starting to run out of ideas.
First idea: Your screenshot shows that there is one error in the console. Was that caused by my package ?
Second idea: Close Atom, delete the contents of `~/.atom/storage` (make sure you don't have any unsaved changes in other instances) and your first `.build-tools.cson` and restart Atom. You did not deactivate the package somehow or the installation failed, right ?

**Comment by isopropylcyanide** [comment]
The second idea fixed it. Thanks for hanging in there :)
