### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by berna1995** [deprint/build-tools-cpp#55]
Hi guys, i'm new to Atom and i'm trying to install build-tools.
This is the output.

> ptyw.js@0.3.7 install C:\Users\Matteo\AppData\Local\Temp\apm-install-dir-116012-9668-b098xe\node_modules\build-tools\node_modules\ptyw.js
> node-gyp rebuild

C:\Users\Matteo\AppData\Local\Temp\apm-install-dir-116012-9668-b098xe\node_modules\build-tools\node_modules\ptyw.js>if not defined npm_config_node_gyp (node "C:\Users\Matteo\AppData\Local\atom\app-1.3.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Matteo\\AppData\\Local\\atom\\app-1.3.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Matteo\\AppData\\Local\\atom\\app-1.3.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Matteo\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Matteo\\.atom\\.apmrc" "install" "C:\\Users\\Matteo\\AppData\\Local\\Temp\\d-116012-9668-v8enaw\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

**Comment by deprint** [comment]
Is `node-gyp` installed correctly, including all dependencies ? https://www.npmjs.com/package/node-gyp

**Comment by Wedmer** [comment]
Why there're no information that I have to install nodejs and node-gyp to use this plugin?

**Comment by deprint** [comment]
1. `node` and `node-gyp` come pre-packaged with Atom. He's probably missing a developer pack or whatever Windows calls these things.
2. It's basically a windows-only issue, because most UNIXes require a compiler at some point (non-Ubuntu users need to compile Atom anyway).
3. People who use Atom (and especially those who use my package) most likely do software development of sorts and thus, it is safe to assume that their set-ups already meet the requirements.

**Comment by berna1995** [comment]
Well i solved the problem, It was the node-gyp missing as you suggested. Thanks.

**Comment by Wedmer** [comment]
It seems that node-gyp bundled with Atom apm does'n work. When npm wants to rebuild it this error occurs.
