### ISSUE TITLE
Does not work with linter any more

### ISSUE THREAD

**Issue by mertzt89** [deprint/build-tools-cpp#60]
I noticed that my parsed errors were not showing up in the linter any more. I believe this is due to changes in the linter API.

**Comment by deprint** [comment]
I know that the linter API changed, but it's still working on my machine, so I didn't update my code.
Which profile do you use ?
Atom version, Linter version, build-tools version ?

**Comment by mertzt89** [comment]
My mistake. In the linter settings it was configure to ignore VCS ignored files and the particular file that i was using to test was VCS ignored! Now that I changed that setting all is well. Thanks.
