### ISSUE TITLE
Configuration screen won't work

### ISSUE THREAD

**Issue by zordtk** [deprint/build-tools-cpp#63]
When I create a new .build-tools.cson and try to open it, the configuration screen doesn't open. I see the following error in the dev log:

Failed to require the main module of 'build-tools' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

I ran apm rebuild in both build-tools package and build-tools-make and both succeed but it still doesn't work. I'm running on Linux using Atom 1.6.2 and version 4.3.4 

Thanks,
Jeremy Harmon

**Comment by deprint** [comment]
I _think_ this problem is related to #46. How did you run `apm rebuild` and did the command succeed ?

**Comment by zordtk** [comment]
I ran apm rebuild from the command-line in the plugin directory, this didn't work even though the build succeeded. After some googling I saw the little red icon in the bottom right and let it rebuild inside the UI and that worked. Not sure what it does differently, but it's working now. Thanks
