### ISSUE TITLE
Error trying to install in Windows

### ISSUE THREAD

**Issue by arm4design** [deprint/build-tools-cpp#65]
Hi, it is throwing the below error when installing it on a Windows x64 machine. Thanks.

> ptyw.js@0.3.7 install C:\Users\ADMINI~1\AppData\Local\Temp\2\apm-install-dir-116313-3692-1n2nnmy\node_modules\build-tools\node_modules\ptyw.js
> node-gyp rebuild

C:\Users\ADMINI~1\AppData\Local\Temp\2\apm-install-dir-116313-3692-1n2nnmy\node_modules\build-tools\node_modules\ptyw.js>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\d-116313-3692-n5xs1q\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

**Comment by thiagohmoreira** [comment]
Having the very same issue here, also windows 10 x64, with Atom 1.8.0-beta2
